# Generated by Django 3.0.4 on 2020-03-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('ags', models.IntegerField(help_text='Amtlicher Gemeindeschlüssel', unique=True)),
                ('gen', models.CharField(blank=True, help_text='Kurzbezeichnung', max_length=90, null=True)),
                ('bez', models.CharField(blank=True, help_text='Typ der Gemeinde, bspw. kreisfreie Stadt', max_length=200, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('population_male', models.BigIntegerField(blank=True, null=True)),
                ('population_female', models.BigIntegerField(blank=True, null=True)),
                ('population_density_km', models.FloatField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.State')),
            ],
            options={
                'unique_together': {('name', 'state', 'ags')},
            },
        ),
    ]
