# Generated by Django 3.0.4 on 2020-03-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_auto_20200322_1609'),
        ('daily_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailycase',
            unique_together={('date_day', 'county')},
        ),
    ]
