# Generated by Django 3.0.4 on 2020-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0002_auto_20200321_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycase',
            name='healed_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
