# Generated by Django 3.0.4 on 2020-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0002_auto_20200322_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genderagerelation',
            name='count',
        ),
        migrations.AddField(
            model_name='genderagerelation',
            name='deaths_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genderagerelation',
            name='infected_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
