# Generated by Django 3.0.4 on 2020-03-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0003_auto_20200325_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
